<?xml version="1.0"?> 
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="M_PI"        value="3.14159"/>
<xacro:property name="base_length" value="1.3"/>
<xacro:property name="base_width"  value="0.8"/>
<xacro:property name="base_height" value="0.2"/>

<xacro:property name="wheel_length" value="0.08"/>
<xacro:property name="wheel_radius" value="0.15"/>

<xacro:property name="wheel_x_offset"    value="0.4"/>
<xacro:property name="wheel_y_offset"    value="0.375"/>
<xacro:property name="wheel_z_offset"    value="-0.055"/>

<material name="yellow">
	<color rgba="1 0.4 0 1"/>
</material>
<material name="black">
	<color rgba="0 0 0 0.9"/>
</material>
<material name="gray">
	<color rgba="0.75 0.75 0.75 1"/>
</material>
<material name="white">
	<color rgba="1 1 1 1"/>
</material>
<material name="blue">  
        <color rgba="0 0 .8 1"/>  
</material>  


<link name="head">
<visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
	<box size=".12 .13 .04"/>
    </geometry>
    <material name="white"/>
</visual>
</link>

<joint name="tobox"  type="fixed">
<origin xyz="0.3 0 0.1" rpy="0 0 0"/>
<parent link="base_link"/>
<child  link="head"/>
</joint>

<link name="base_link">  
<visual> 
<geometry>  
  <box size="${base_length} ${base_width} ${base_height}"/>  
</geometry>  
<origin rpy="0 0 0" xyz="0 0 0"/>
<material name="blue"/>  
</visual>  
</link>

<xacro:macro name="steer_wheel" params="prefix reflect">

    <link name="${prefix}_front_wheel">
    	<visual>
	    <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
	    <geometry>
		<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
	    </geometry>
	    <material name="black"/>
        </visual>
    </link>

    <joint name="${prefix}_front_steer_joint"  type="revolute">
	<origin xyz="${wheel_x_offset} ${reflect*wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
	<limit effort ="1000.0" lower="-1" upper="1" velocity="0.5"/>
	<parent link="base_link"/>
	<child  link="${prefix}_front_wheel"/>
	<axis   xyz="0 1 0"/>
    </joint>
</xacro:macro>

<xacro:macro name="drive_wheel" params="prefix reflect">

    <link name="${prefix}_rear_wheel">
    	<visual>
	    <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
	    <geometry>
		<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
	    </geometry>
	    <material name="black"/>
        </visual>
    </link>

    <joint name="${prefix}_rear_drive_joint"  type="revolute">
	<origin xyz="${-1*wheel_x_offset} ${reflect*wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
	<limit effort ="1000.0" lower="-1" upper="1" velocity="0.5"/>
	<parent link="base_link"/>
	<child  link="${prefix}_rear_wheel"/>
	<axis   xyz="0 1 0"/>
    </joint>
</xacro:macro>

<steer_wheel prefix="left"  reflect="1"/>
<steer_wheel prefix="right" reflect="-1"/>
<drive_wheel prefix="left"  reflect="1"/>
<drive_wheel prefix="right" reflect="-1"/>

</robot>
